name:                LambdaCalculus
version:             0.1.0.0
github:              "breakerzirconia/LambdaCalculus"
license:             BSD3
author:              "Constantine Ter-Matevosian"
maintainer:          "terkot1010@gmail.com"
copyright:           "2020 Constantine Ter-Matevosian"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/breakerzirconia/LambdaCalculus#readme>

dependencies:
- base >= 4.7 && < 5
- text
- hspec
- tasty-quickcheck
- tasty
- containers

library:
  source-dirs: src

executables:
  LambdaCalculus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambdaCalculus

tests:
  LambdaCalculus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambdaCalculus
